name: Scan Markdown Files for 404 Errors

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily (adjust as needed)
  workflow_dispatch: # Allows manual triggering

jobs:
  scan-404-errors:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install necessary tools
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y curl grep sed

      # Step 3: Scan Markdown files for broken links
      - name: Scan Markdown Files for Broken Links
        run: |
          echo "Scanning Markdown files for broken links..."
          touch markdown-404-errors.log # Ensure log file is created
          find . -name "*.md" | while read -r file; do
            echo "Processing $file..."
            grep -oP '(?<=\]\().*?(?=\))' "$file" | while read -r link; do
              if [[ $link == http* ]]; then
                status_code=$(curl -o /dev/null -s -w "%{http_code}" "$link")
                if [ "$status_code" == "000" ]; then
                  echo "Malformed URL or network issue in $file: $link" >> markdown-404-errors.log
                elif [ "$status_code" == "404" ]; then
                  echo "404 Error in $file: $link" >> markdown-404-errors.log
                fi
              fi
            done || true
          done

          # Debugging step to check if log file is empty
          if [ ! -s markdown-404-errors.log ]; then
            echo "No 404 errors found or no links processed." >> markdown-404-errors.log
          fi

      # Step 4: Upload the log file as an artifact
      - name: Upload Log File
        uses: actions/upload-artifact@v4
        with:
          name: markdown-404-errors
          path: markdown-404-errors.log
